apiVersion: v1
kind: ServiceAccount
metadata:
  name: experience-order-tracker-service
  namespace: apps
  labels:
    app.kubernetes.io/name: experience-order-tracker-service
    app.kubernetes.io/part-of: apps
