apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: apps
  labels:
    app.kubernetes.io/name: tracking-service
    app.kubernetes.io/part-of: apps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tracking-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
